name: Deploy to HostMyCode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write SSH key to file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.CPANEL_PORT }} ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts

    - name: Upload via SCP
      run: |
        scp -r -P ${{ secrets.CPANEL_PORT }} ./* ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }}:/home/${{ secrets.CPANEL_USERNAME }}/public_html/${{ secrets.CPANEL_APP_PATH }}

    - name: Restart Node App
      run: |
        ssh -p ${{ secrets.CPANEL_PORT }} ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} << 'EOF'
          source ~/nodevenv/${{ secrets.CPANEL_APP_PATH }}/18/bin/activate
          cd ~/public_html/${{ secrets.CPANEL_APP_PATH }}
          npm install --omit=dev
          touch tmp/restart.txt || echo "No restart file needed"
        EOF
