name: Deploy to HostMyCode via SSH
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
 
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.CPANEL_PORT }} ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts
 
    - name: Deploy files to cPanel via rsync
      run: |
        rsync -avz --delete -e "ssh -p ${{ secrets.CPANEL_PORT }}" ./ ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }}:public_html/${{ secrets.CPANEL_APP_PATH }}/
 
    - name: Restart Node.js App
      run: |
        ssh -p ${{ secrets.CPANEL_PORT }} ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_HOST }} << 'EOF'
          source ~/nodevenv/${{ secrets.CPANEL_APP_PATH }}/18/bin/activate
          cd ~/public_html/${{ secrets.CPANEL_APP_PATH }}
          npm install --omit=dev
          touch tmp/restart.txt || echo "Restart signal file not found (not needed)"
        EOF